apiVersion: apps/v1
kind: Deployment
metadata:
  name: $ENV-$PROJECT-deployment
  namespace: default
  labels:
    app: $ENV-$PROJECT-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $ENV-$PROJECT-pod
  template:
    metadata:
      name: $ENV-$PROJECT-pod
      namespace: default
      labels:
        app: $ENV-$PROJECT-pod
    spec:
      volumes:
        - name: $ENV-$PROJECT-secret-env
          secret:
            secretName: $ENV-$PROJECT-secret-env
      containers:
      - name: $ENV-$PROJECT-container
        image: $IMAGE
        ports:
          - containerPort: $CONTAINER_PORT
        resources:
          requests:
            memory: '600Mi'
            cpu: '200m'
          limits:
            memory: '600Mi'
        volumeMounts:
          - name: $ENV-$PROJECT-secret-env
            readOnly: true
            mountPath: "/secret-env"
