apiVersion: v1
kind: Service
metadata:
  name: $SVC_NAME
  namespace: default
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: $LB_CERT_ARN
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
spec:
  type: LoadBalancer
  selector:
    app: $SVC_SELECTOR
  ports:
    - port: 443
      targetPort: $SVC_TARGET_PORT
      name: https